### ISSUE TITLE
Cannot convert tables in md

### ISSUE THREAD

**Issue by tikaa** [njvack/bids-json-writer#11]
I have an md with a table and tried using this tool to convert it. But seems this only supports basic simple mds. I get the following error,
"markdown_to_json.markdown_to_json.ContentError: Error at line 47: Can't mix lists and other content"

Do you have any plans on improvements?

**Comment by njvack** [comment]
Hi Tikaa,

I'm not sure what a table would do in a json file... maybe... a nested array or something?

This is really mainly intended for basic, simple mds, where you want to write documentation that needs to be turned into .json. If you want to do something complicated, probably just write the json, or use yaml and turn that into json.

I'd love to improve this, but it's not super high in my priorities; when I made the tool, it was for work, but improving it would definitely fall into the "hobby" category.

**Comment by njvack** [comment]
On (much) later reflection, I'm not planning table support here

**Comment by matthewdeanmartin** [comment]
[markpickle](https://pypi.org/project/markpickle) supports tables. Because there are at least 3 ways to convert a table to python, you may need to set the preferred style in the config.

example - https://github.com/matthewdeanmartin/markpickle/blob/main/test/test_deserialize/test_dicts_as_tables.py#L16
