### ISSUE TITLE
Pandoc compatibility?

### ISSUE THREAD

**Issue by gwerbin** [njvack/bids-json-writer#3]
Is this compatible with the Pandoc JSON format?

**Comment by njvack** [comment]
I'm not familiar with it. Can you link to any docs?

**Comment by njvack** [comment]
I know this issue is ancient, but I'm looking into this a bit, and it might be possible? What are you hoping to do with the JSON output? Would there be benefit in generating this style JSON with this converter as opposed to using Pandoc directly?

The intent of this is really to generate configuration-style output from a markdown file, rather than generate a full AST from a Markdown file, though.

**Comment by matthewdeanmartin** [comment]
The answer is "no". Having recently tried to upgrade this library to the "successor" of CommonMark, this library's internal expect CommonMark's DOM and if you attempt to pass it some other parser's DOM, it won't work with out a massive rewrite.

This use case doesn't make a lot of sense though because the public interface of the library is to turn Markdown into python dictionaries.

**Comment by njvack** [comment]
yeah I looked into switching markdown parsers a while ago and even changing commonmark versions is not trivial; we're rummaging around in the internals.
